apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fooddelivery-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 3000
      # - path: /api/users
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: user-service-service
      #       port:
      #         number: 3001
      # - path: /api/restaurants
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: restaurant-service-service
      #       port:
      #         number: 3002
      # - path: /api/orders
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: order-service-service
      #       port:
      #         number: 3003
      # - path: /api/notifications
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: notification-service-service
      #       port:
      #         number: 3004
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 5173